workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "ios/ExoticBasket.xcworkspace" \
            --scheme "ExoticBasket"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
