// Auth
export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';
export const OTPVERIFICATION = 'OTPVERIFICATION';
export const RESEDNOTP = 'RESEDNOTP';
export const PRODUCT = 'PRODUCT';
export const PRODUCTPAGE = 'PRODUCTPAGE';
export const CATEGORY = 'CATEGORY';
export const ADDTOCART = 'ADDTOCART';

export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const ADD_TO_CART = 'ADD_TO_CART';

export const CART = 'CART';
export const REMOVEFROMCART = 'REMOVEFROMCART';
export const DELETEALLITEMCART = 'DELETEALLITEMCART';
export const VIEWORDERHISTORY = 'VIEWORDERHISTORY';
export const VIEWORDERDETAILSLIST = 'VIEWORDERDETAILSLIST';
export const PAYMENT = 'PAYMENT';
export const SELECTEDADDRRES = 'SELECTEDADDRRES';
export const ADDRRESS = 'ADDRRESS';
export const ITEMSEARCH = 'ITEMSEARCH';
export const CATEGORYITEMS = 'CATEGORYITEMS';
export const SELECTEDCATEGORYITEMS = 'SELECTEDCATEGORYITEMS';
export const PAYMENTREFRENCE = 'PAYMENTREFRENCE';
export const KYC_DATA = 'KYC_DATA';
export const CATEGORYITEMPAGE = 'CATEGORYITEMPAGE';
export const NOCATEGORYDATA = 'NOCATEGORYDATA';
export const DELIVERYCHARGES = 'DELIVERYCHARGES';
export const MINIMUMORDERVALUE = 'MINIMUMORDERVALUE';
export const ISLOADING = 'ISLOADING';
export const DropDownCity = 'DropDownCity';
export const SELECTEDCITY = 'SELECTEDCITY';
export const CITY = 'CITY';
export const BOTHID = 'BOTHID';
export const RESET = 'RESET';
export const WALLETBALANCE = 'WALLETBALANCE';
export const ALLCOUPAN = 'ALLCOUPAN';
export const APPLYCOUPAN = 'APPLYCOUPAN';

export const MASTERCATEGORY = 'MASTERCATEGORY';
export const SUBCATEGORY = 'SUBCATEGORY';
export const SUBCATEGORYITEMS = 'SUBCATEGORYITEMS';
export const SELECTEDMASTERCATEGORY = 'SELECTEDMASTERCATEGORY';
export const SELECTEDSUBCATEGORY = 'SELECTEDSUBCATEGORY';
export const SUBCATEGORYITEMPAGE = 'SUBCATEGORYITEMPAGE';
export const SUBCATEGORYITEMTOTALPAGE = 'SUBCATEGORYITEMTOTALPAGE';
export const ADD_SUBCATEGORYITEMS = 'ADD_SUBCATEGORYITEMS';
export const RECOMMENDED_TOTAL_PAGE = 'RECOMMENDED_TOTA_PAGE';

// SelllerSide
export const ORDERVIEWORDER = 'ORDERVIEWORDER';
export const GETORDERMASTERDETAILSTYPE = 'GETORDERMASTERDETAILSTYPE';
export const CUSTMOREADDRESSID = 'CUSTMOREADDRESSID';
export const ORDERVIEWORDERONE = 'ORDERVIEWORDERONE';
export const SUPPLIERLIST = 'SUPPLIERLIST';
